[package]
name = "anifunnel"
version = "1.0.2"
edition = "2021"
resolver = "2"

[dependencies]
clap = { version = "4.0.29", features = ["derive", "env"] }
log = "0.4"
regex = "1.5"
rocket = "0.5.0-rc.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple_logger = "4.0.0"
strsim = "0.10.0"

[target.'cfg(target_os = "linux")'.dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json", "default-tls"] }
